### ISSUE TITLE
Unable to find starter template for super

### ISSUE THREAD

**Issue by besi** [driftyco/ionic-starter-super#108] opened 2017-05-15 11:53 UTC
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I run the following command:

    $ ionic start mySuperApp super

And I get the error:

> ✖ Creating directory /Users/besi/Desktop/mySuperApp - failed!
> Unable to find starter template for super

I have ionic installed:

    $ ionic -v
    3.0.0

**Expected behavior:**
I would expect the template app to be created

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

System:

    Node       : v7.4.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13 
```

**Comment by piotrowski** [comment] 2017-05-15 14:45
The super starter is not yet part of Ionic CLI v3 - you will have to wait for the next release of that or use CLI v2.2.3 to create a project with the super starter. Here is the (already merged) Pull Request for this: https://github.com/driftyco/ionic-cli/pull/2269

I will keep this issue open until the next version is released and the problem is actually, really resolved.

**Comment by davidgv88** [comment] 2017-05-15 14:48
I have the same problem.

Today I updated to 3.X. The Ionic Super Starter template is not compatible with Ionic CLI v 3.X.

With 2.X works ok

**Comment by piotrowski** [comment] 2017-05-15 14:52
> The Ionic Super Starter template is not compatible with Ionic CLI v 3.X.

It is fully compatible, it just was not included in the list of valid starters in v3.0.0

**Comment by davidgv88** [comment] 2017-05-15 15:00
Sorry what I meant is that after the upgraded to version 3.x, it stop working.

**Comment by danielsogl** [comment] 2017-05-17 07:45
@besi I close this issue.
Install the latest CLI with `npm install -g ionic@latest` and you should be able to download the super template.

**Closed by danielsogl** 2017-05-17 07:45 UTC
