### ISSUE TITLE
input fields not working

### ISSUE THREAD

**Issue by jfoscue** [driftyco/ionic-starter-super#72] opened 2017-01-19 22:08 UTC
I am testing with the item-create page and whenever I click on any input nothing works.

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.10
Ionic App Lib Version: 2.1.6
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by selloutdesign** [comment] 2017-01-19 22:20
I just started up a fresh install and works perfect for me. How are you testing it?
<img width="525" alt="myapp_-_ionic_lab" src="https://cloud.githubusercontent.com/assets/1129154/22127784/5ee49d92-de52-11e6-97dc-55e8a60f682f.png">

**Comment by jfoscue** [comment] 2017-01-19 22:27
Running "ionic emulate ios".

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.10
Ionic App Lib Version: 2.1.6
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 8.2.1 Build version 8C1002

I’m thinking something strange with versions I have but haven’t figured it out yet.

Thanks for your help!

**Comment by selloutdesign** [comment] 2017-01-20 03:19
The inputs are a little tricky in the emulator. I had to manually turn on the keyboard once. 
Are you hitting the 'Done' button in the top right after entering your item?.

**Comment by wbhob** [comment] 2017-01-20 20:45
Type `ionic serve` in your command line for faster testing, then test on a device/emulator later. For the sake of rapid development, `serve` is great for getting an idea of how your app works and feels, and updating quickly. Then, when you are doing platform tweaks, then you move to your emulator.

Regards,
Wilson

**Comment by jfoscue** [comment] 2017-01-20 21:08
I do use serve for rapid development but this still doesn't explain why it
doesn't work in the emulator.  It used to work there too.

**Comment by danielsogl** [comment] 2017-05-12 06:02
I can't reproduce this issue. I close it.
Feel free to reopen it if you still have problems after updating to the latest release.

**Closed by danielsogl** 2017-05-12 06:02 UTC
